// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using compiled_models.Chinook;
using compiled_models.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ChinookContext), typeof(ChinookContextModel))]
