// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace compiled_models.CompiledModels
{
    public partial class ChinookContextModel
    {
        private ChinookContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("1e189dae-375c-42ec-bac9-50d6b69a84cb"), entityTypeCount: 11)
        {
        }

        partial void Initialize()
        {
            var playlistTrack = PlaylistTrackEntityType.Create(this);
            var album = AlbumEntityType.Create(this);
            var artist = ArtistEntityType.Create(this);
            var customer = CustomerEntityType.Create(this);
            var employee = EmployeeEntityType.Create(this);
            var genre = GenreEntityType.Create(this);
            var invoice = InvoiceEntityType.Create(this);
            var invoiceLine = InvoiceLineEntityType.Create(this);
            var mediaType = MediaTypeEntityType.Create(this);
            var playlist = PlaylistEntityType.Create(this);
            var track = TrackEntityType.Create(this);

            PlaylistTrackEntityType.CreateForeignKey1(playlistTrack, playlist);
            PlaylistTrackEntityType.CreateForeignKey2(playlistTrack, track);
            AlbumEntityType.CreateForeignKey1(album, artist);
            CustomerEntityType.CreateForeignKey1(customer, employee);
            EmployeeEntityType.CreateForeignKey1(employee, employee);
            InvoiceEntityType.CreateForeignKey1(invoice, customer);
            InvoiceLineEntityType.CreateForeignKey1(invoiceLine, invoice);
            InvoiceLineEntityType.CreateForeignKey2(invoiceLine, track);
            TrackEntityType.CreateForeignKey1(track, album);
            TrackEntityType.CreateForeignKey2(track, genre);
            TrackEntityType.CreateForeignKey3(track, mediaType);

            PlaylistEntityType.CreateSkipNavigation1(playlist, track, playlistTrack);
            TrackEntityType.CreateSkipNavigation1(track, playlist, playlistTrack);

            PlaylistTrackEntityType.CreateAnnotations(playlistTrack);
            AlbumEntityType.CreateAnnotations(album);
            ArtistEntityType.CreateAnnotations(artist);
            CustomerEntityType.CreateAnnotations(customer);
            EmployeeEntityType.CreateAnnotations(employee);
            GenreEntityType.CreateAnnotations(genre);
            InvoiceEntityType.CreateAnnotations(invoice);
            InvoiceLineEntityType.CreateAnnotations(invoiceLine);
            MediaTypeEntityType.CreateAnnotations(mediaType);
            PlaylistEntityType.CreateAnnotations(playlist);
            TrackEntityType.CreateAnnotations(track);

            AddAnnotation("ProductVersion", "10.0.12");
        }
    }
}
