// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using compiled_models.Chinook;

#pragma warning disable 219, 612, 618
#nullable disable

namespace compiled_models.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class InvoiceLineEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "compiled_models.Chinook.InvoiceLine",
                typeof(InvoiceLine),
                baseEntityType,
                propertyCount: 5,
                navigationCount: 2,
                foreignKeyCount: 2,
                namedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(BaseEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var invoiceId = runtimeEntityType.AddProperty(
                "InvoiceId",
                typeof(int),
                propertyInfo: typeof(InvoiceLine).GetProperty("InvoiceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InvoiceLine).GetField("<InvoiceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var quantity = runtimeEntityType.AddProperty(
                "Quantity",
                typeof(int),
                propertyInfo: typeof(InvoiceLine).GetProperty("Quantity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InvoiceLine).GetField("<Quantity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var trackId = runtimeEntityType.AddProperty(
                "TrackId",
                typeof(int),
                propertyInfo: typeof(InvoiceLine).GetProperty("TrackId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InvoiceLine).GetField("<TrackId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var unitPrice = runtimeEntityType.AddProperty(
                "UnitPrice",
                typeof(decimal),
                propertyInfo: typeof(InvoiceLine).GetProperty("UnitPrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InvoiceLine).GetField("<UnitPrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            unitPrice.AddAnnotation("Relational:ColumnType", "numeric(10, 2)");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "PK__InvoiceL__0D760AD91DE57479");

            var iFK_Invoice_InvoiceLine = runtimeEntityType.AddIndex(
                new[] { invoiceId },
                name: "IFK_Invoice_InvoiceLine");

            var iFK_ProductItem_InvoiceLine = runtimeEntityType.AddIndex(
                new[] { trackId },
                name: "IFK_ProductItem_InvoiceLine");

            var iPK_InvoiceLine = runtimeEntityType.AddIndex(
                new[] { id },
                name: "IPK_InvoiceLine");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("InvoiceId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                required: true);

            var invoice = declaringEntityType.AddNavigation("Invoice",
                runtimeForeignKey,
                onDependent: true,
                typeof(Invoice),
                propertyInfo: typeof(InvoiceLine).GetProperty("Invoice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InvoiceLine).GetField("<Invoice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var invoiceLines = principalEntityType.AddNavigation("InvoiceLines",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<InvoiceLine>),
                propertyInfo: typeof(Invoice).GetProperty("InvoiceLines", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Invoice).GetField("<InvoiceLines>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK__InvoiceLi__Invoi__2F10007B");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("TrackId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                required: true);

            var track = declaringEntityType.AddNavigation("Track",
                runtimeForeignKey,
                onDependent: true,
                typeof(Track),
                propertyInfo: typeof(InvoiceLine).GetProperty("Track", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InvoiceLine).GetField("<Track>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var invoiceLines = principalEntityType.AddNavigation("InvoiceLines",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<InvoiceLine>),
                propertyInfo: typeof(Track).GetProperty("InvoiceLines", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Track).GetField("<InvoiceLines>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK__InvoiceLi__Track__2E1BDC42");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "InvoiceLine");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
