<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>ef_core_sprocs_perf</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
    </ItemGroup>

</Project>
