extern alias lazy_loading;

using System.Diagnostics;
using EFCoreDemos.Tests.Infrastructure;
using lazy_loading::lazy_loading.Chinook;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Xunit;

namespace EFCoreDemos.Tests.Demos
{
    /// <summary>
    /// lazy-loading: UseLazyLoadingProxies makes navigations load on first access, one round-trip per
    /// not-yet-tracked related entity (the N+1). Already-tracked artists are reused via identity resolution.
    /// The demo's ChinookContext only has a parameterless constructor, so SQL is counted through EF's
    /// DiagnosticListener (filtered to the test's context instance) instead of a LogTo hook.
    /// </summary>
    public class LazyLoadingTests : IDisposable
    {
        private readonly ChinookCopy _db = new();

        public void Dispose() => _db.Dispose();

        private ChinookContext CreateContext() => _db.Redirect(new ChinookContext());

        [Fact]
        public void Entities_AreLazyLoadingProxies()
        {
            using var db = CreateContext();

            var album = db.Albums.OrderBy(a => a.Id).First();

            // Castle proxy subclass generated by UseLazyLoadingProxies.
            Assert.NotEqual(typeof(Album), album.GetType());
            Assert.Equal(typeof(Album), album.GetType().BaseType);
        }

        [Fact]
        public void TouchingNavigation_LoadsItOnDemand()
        {
            using var db = CreateContext();

            var album = db.Albums.OrderBy(a => a.Id).First();
            var reference = db.Entry(album).Reference(a => a.Artist);
            Assert.False(reference.IsLoaded);

            var artist = album.Artist;

            Assert.NotNull(artist);
            Assert.True(reference.IsLoaded);
            Assert.Equal(album.ArtistId, artist.Id);
        }

        [Fact]
        public void LoopOverAlbums_IssuesOneQueryPerDistinctArtist()
        {
            using var db = CreateContext();
            using var counter = new CommandCounter(db);

            var albums = db.Albums.OrderBy(a => a.Id).Take(5).ToList();
            Assert.Equal(1, counter.Count);

            foreach (var album in albums)
            {
                Assert.NotNull(album.Artist);
            }

            var distinctArtists = albums.Select(a => a.ArtistId).Distinct().Count();
            Assert.Equal(3, distinctArtists);
            // 1 SELECT for the albums + 1 per distinct artist; repeat artists come from the change tracker.
            Assert.Equal(1 + distinctArtists, counter.Count);
        }

        [Fact]
        public void Include_AvoidsTheExtraRoundTrips()
        {
            using var db = CreateContext();
            using var counter = new CommandCounter(db);

            var albums = db.Albums.Include(a => a.Artist).OrderBy(a => a.Id).Take(5).ToList();
            foreach (var album in albums)
            {
                Assert.NotNull(album.Artist);
            }

            Assert.Equal(1, counter.Count);
        }

        /// <summary>Counts CommandExecuted diagnostic events raised by one specific context instance.</summary>
        private sealed class CommandCounter : IObserver<DiagnosticListener>, IObserver<KeyValuePair<string, object?>>, IDisposable
        {
            private readonly DbContext _context;
            private readonly List<IDisposable> _subscriptions = [];
            private readonly IDisposable _allListeners;
            private int _count;

            public CommandCounter(DbContext context)
            {
                _context = context;
                _allListeners = DiagnosticListener.AllListeners.Subscribe(this);
            }

            public int Count => Volatile.Read(ref _count);

            void IObserver<DiagnosticListener>.OnNext(DiagnosticListener listener)
            {
                if (listener.Name == DbLoggerCategory.Name)
                {
                    var subscription = listener.Subscribe(this, name => name == RelationalEventId.CommandExecuted.Name);
                    lock (_subscriptions) _subscriptions.Add(subscription);
                }
            }

            void IObserver<KeyValuePair<string, object?>>.OnNext(KeyValuePair<string, object?> value)
            {
                if (value.Value is CommandExecutedEventData data && ReferenceEquals(data.Context, _context))
                {
                    Interlocked.Increment(ref _count);
                }
            }

            void IObserver<DiagnosticListener>.OnCompleted() { }
            void IObserver<DiagnosticListener>.OnError(Exception error) { }
            void IObserver<KeyValuePair<string, object?>>.OnCompleted() { }
            void IObserver<KeyValuePair<string, object?>>.OnError(Exception error) { }

            public void Dispose()
            {
                _allListeners.Dispose();
                lock (_subscriptions)
                {
                    foreach (var subscription in _subscriptions) subscription.Dispose();
                    _subscriptions.Clear();
                }
            }
        }
    }
}
